[package]
name = "Simple_Kor_IME"
version = "0.1.0"
authors = [
    "KeyvanOh <https://github.com/KeyvanOh>",
]
edition = "2021"

[dependencies]
pixels = "0.13.0"
winit = "0.28.7"
rustkorean = "1.1.0"
